version: '3.8'
services:
  app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: ./app
    environment:
      IMAGES_URL: http://localhost:8080
    ports:
      - "8081:8080"

  image-store:
    container_name: image-store
    build:
      dockerfile: Dockerfile
      context: ./image-store
    ports:
      - "8080:80"
